name: BW-EA Organizations Base CI/CD Workflow Template

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
  # Needed to execute workflow manually -> https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Permissions block is optional, useful for dependabot checks 
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      checks: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
